# Site Settings
locale: "en-US"
title: "Junteng Liu"
title_separator: "|"
subtitle: "PhD candidate in Computer Science"
name: "Junteng Liu"
description: "Personal homepage of Junteng Liu, a first-year PhD candidate at HKUST NLP Group."
url: "https://nggokkhts3704.github.io"
baseurl: "/LJT-Homepage"
repository: "nggokkhts3704/LJT-Homepage"
email: "jliugi@connect.ust.hk"
github_username: "Vicent0205"
twitter_username: "junteng88716710"
search: false
atom_feed:
  hide: true

analytics:
  provider: false

comments:
  provider: false

# Site Author
author:
  name: "Junteng Liu"
  bio: "First-year PhD candidate at HKUST NLP Group. Research focuses on natural language processing and machine learning."
  employer: "Hong Kong University of Science and Technology"
  email: "jliugi@connect.ust.hk"
  github: "Vicent0205"
  twitter: "junteng88716710"
  googlescholar: "https://scholar.google.com/citations?hl=en&user=tbK9jl4AAAAJ&view_op=list_works&sortby=pubdate"

# Reading Files
include:
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
  - /docs
  - /test
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Content Settings
read_more: disabled
show_excerpts: false

# Collections
collections:
  publications:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/
  posts:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/
  teaching:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: false
      share: false
      related: false
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  # _publications
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
      share: false
      comments: false
  # _portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: true
      share: false
  # _talks
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
      author_profile: true
      share: false
  # _teaching
  - scope:
      path: ""
      type: teaching
    values:
      layout: single
      author_profile: true
      share: false
      comments: false

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# Outputting
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# Markdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Sass
sass:
  sass_dir: _sass
  style: compressed
